version: "3"

services:

  mongo:
    image: mongo
    container_name: "mongo"
    ports:
      - '27017:27017'

  redis:
    image: redis
    container_name: "redis"
    ports:
      - '6379:6379'

  frontend:
    container_name: "frontend"
    build: ../immutable-redux
    environment:
      env_file: .env
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - ../immutable-redux/src:/usr/src/app/src

  backend:
    depends_on:
      - mongo
      - redis
    container_name: "backend"
    build: ../immutable-redux-server
    links:
      - mongo
    environment:
      env_file: .env
      NODE_ENV: development
      DOCKER_DB: 27107
    ports:
      - '8081:8081'
    volumes:
      - ../immutable-redux-server/src:/usr/src/app/src

  emitter:
    container_name: "emitter"
    build: ../emitter-server
    links:
      - mongo
    environment:
      env_file: .env
      NODE_ENV: development
      DOCKER: 'true'
    ports:
      - '8080:8080'
    volumes:
      - ../emitter-server/src:/usr/src/app/src
